cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(passthru C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()

add_executable(passthru main.c usb_descriptors.c)
pico_generate_pio_header(passthru ${CMAKE_CURRENT_LIST_DIR}/pio_uart.pio)
target_include_directories(passthru PRIVATE ${CMAKE_CURRENT_LIST_DIR})
target_link_libraries(passthru pico_stdlib hardware_pio tinyusb_device tinyusb_board)
pico_add_extra_outputs(passthru)
